### ISSUE TITLE
add media query style to make article grid three columns

### ISSUE THREAD

**Issue by annechinn** [annechinn/news-site-collab#10]
below is the format for a media query style. it is already in the styles.css file, but is currently empty.
add the correct styles within it to make the article grid have three columns when screen with>=600px.

@media screen and (min-width: 600px) {
}

**Comment by AJ-Brown-InTech** [comment]
having a little bit of trouble with this one i put :

@media  (min-width: 600px) {
display: grid;
grid-template-columns: 1fr 1fr 1fr;
}

i moved it to the bottom of the style sheet and it did not work
