### ISSUE TITLE
Add a Readme file

### ISSUE THREAD

**Issue by liambrewster** [annechinn/news-site-collab#21]
Add a readme file which states contribution is limited to a small selection of Bootcamp students!

and i want to wish all the student all the best and go smash your journey!!!!!

**Comment by annechinn** [comment]
Thanks! It's my first class I'm teaching and quickly put together the site for this week's class. You're quite quick to find it...

**Comment by liambrewster** [comment]
learning myself and wanted to get more involved with github, so trying to find some issues I can contribute with, 

I used this method ( https://www.youtube.com/watch?v=W7AewHnxMig ) and you popped up in the list with some tasty looking issues for me to have a go at.

I enjoyed working on them and appreciate you putting it up

keep up the good work
