### ISSUE TITLE
change category pill text color to white

### ISSUE THREAD

**Issue by annechinn** [annechinn/news-site-collab#25]
![Image 11](https://user-images.githubusercontent.com/12981373/120907160-2659d880-c614-11eb-8ceb-7c793703f2f8.png)

**Comment by annechinn** [comment]
change the text color for all category pills, not just the one in the showcase section.

**Comment by aniketartani** [comment]
Assign me, I will do it asap.

**Comment by eduardarakelyan** [comment]
Hello,
I have completed this task.
